### ISSUE TITLE
projects文件下没有CAP文件夹？

### ISSUE THREAD

**Issue by zhangxin1995** [weleen/MGH.pytorch#1]
我在运行reproduce时发现projects文件下没有CAP文件夹？是不是忘记了

**Comment by weleen** [comment]
@zhangxin1995 因为CAP已经开源，所以没有在projects中放CAP代码，如果有需要可以参考https://github.com/Terminator8758/CAP-master。

**Comment by zhangxin1995** [comment]
但是MGH的repoduce里面的配置文件指向CAP的，所以不能直接运行是么

**Comment by weleen** [comment]
不好意思，我忘记修改reproduce.sh中的路径。把CAP替换成MGH就可以运行了。

**Comment by zhangxin1995** [comment]
好的 谢谢回答
